### ISSUE TITLE
not found this file [Universal Recognition]

### ISSUE THREAD

**Issue by erquren** [QwenLM/Qwen3-VL#1476]
[Universal Recognition](https://github.com/QwenLM/Qwen3-VL/blob/main/cookbooks/universal_recognition.ipynb)
not found this file

**Comment by scutyuanzhi** [comment]
We fixed the link, please try again

**Comment by erquren** [comment]
> We fixed the link, please try again

the after the github url ,colab url is not update

https://colab.research.google.com/github/QwenLM/Qwen3-VL/blob/main/cookbooks/universal_recognition.ipynb
still not found

**Comment by erquren** [comment]
> > We fixed the link, please try again
> 
> the after the github url ,colab url is not update
> 
> https://colab.research.google.com/github/QwenLM/Qwen3-VL/blob/main/cookbooks/universal_recognition.ipynb still not found

this pr update 
https://github.com/QwenLM/Qwen3-VL/pull/1481

**Comment by scutyuanzhi** [comment]
thanks, we have merged

> > > We fixed the link, please try again
> > 
> > 
> > the after the github url ,colab url is not update
> > https://colab.research.google.com/github/QwenLM/Qwen3-VL/blob/main/cookbooks/universal_recognition.ipynb still not found
> 
> this pr update [#1481](https://github.com/QwenLM/Qwen3-VL/pull/1481)
